### PR TITLE
method for useStore

### PR DESCRIPTION
**Pull request by aleksandrjet**
what do u think? i hope, using of store will be easier, because i will not need additional import useStore

instead:
```
const store = atom()
const value = useStore(atom)
```

i would use:
```
const store = atom()
const value = store.use()
```

### CODE REVIEW

**Comment by aleksandrjet** [comment]
if it is good idea, i will write the same for computed and map stores

**Comment by ai** [comment]
But how do you see it on non-React environment. Do they have `use()` method in JS bundles even if they don't need it?

**Comment by aleksandrjet** [comment]
i offer to add this method only for `@nanostores/react`, and want to users use only `import { atom } from '@nanostores/react'` in react projects

**Comment by ai** [comment]
How it will work with stores from `npm` like https://github.com/nanostores/persistent ?

**Comment by aleksandrjet** [comment]
i thought about it, and i see next ways: 
- need to add `@nanostores/persistent` to optional dependencies
- add to another file the same functional for persistent atom
- the installation of `@nanostores/persistent` will be left to the discretion of users
- add checking of existing this dependency for using this functional

or:
- add `@nanostores/persistent` as peerDependencies. i think it will not increase build size, if users don't use it

or do nothing with it, users will use `useStore(persistStore)` as before

**Comment by ai** [comment]
Sorry, it doesn’t look like a good API changes for me:

1. `atom()` from `nanostores` and `atom()` from `@nanostores/react` have the same name but different methods. It could lead to confusions.
2. It is not really compatible with stores from npm like `@nanostores/query`, `router` or `persistent`. It is core benefit of Nano Store but all solutions are hacky.
3. `atom.use()` doesn’t improve DX, it is only subjective changes.

**Pull request closed without merging**
